version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@octokit/webhooks"
    versions:
    - 8.0.2
    - 8.0.3
    - 8.10.1
    - 8.11.2
    - 8.12.0
    - 8.12.2
    - 8.4.0
    - 8.4.1
    - 8.5.0
    - 8.5.1
    - 8.5.2
    - 8.5.3
    - 8.5.4
    - 8.7.0
    - 8.7.1
    - 8.7.2
    - 8.8.0
    - 8.8.3
    - 9.0.0
    - 9.0.1
    - 9.1.0
    - 9.1.1
